name: "Build web export and release on itch io"
on:
  push:
    tags:
      - '**'

env:
  GODOT_VERSION: 4.4.1
  EXPORT_NAME: unseen-hero
  ITCHIO_USERNAME: indigomountain
  ITCHIO_GAME: unseen-hero
  BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
  
jobs:
  export-web:
    name: Web Export
    runs-on: ubuntu-24.04
    container:
      image: barichello/godot-ci:4.4.1@sha256:274a9a1849ec64d0ce8577ccf698bd1b97f9994c150a8e9783e561533e568708
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Build Web
        run: |
          mkdir -v -p build/web
          godot -v --export-release "Web" --headless ./build/web/index.html
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: web
          path: build/web
      - name: Release on itch.io
        run: |
          butler push ./build/web $ITCHIO_USERNAME/$ITCHIO_GAME:web
          